# -*- coding: utf-8 -*-
"""Data science

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1y_TUnQnbVCpBpN8KR9tDZdLFOWq2cZdn
"""

# Commented out IPython magic to ensure Python compatibility.
#please upload dataset file before running.
# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
data = pd.read_csv('PS_dataset.csv')

quality_counts = data['quality'].value_counts().sort_index()
plt.figure(figsize=(10, 6))
quality_counts.plot(kind='bar')
plt.title('No of Wines by Quality Score')
plt.xlabel('Quality Score')
plt.ylabel('No of wines')
plt.xticks(rotation=0)
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data= pd.read_csv('PS_dataset.csv')
plt.figure(figsize=(10,6))
plt.scatter(data['alcohol'],data['pH'],alpha=0.4)
plt.xlabel('Alcohol')
plt.ylabel('pH')
plt.title('variation of pH at particular percentage of alcohol')
plt.show()
print(f"corelational between alcohol and pH: {data['alcohol'].corr(data['pH']):.3f}")

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('PS_dataset.csv')
plt.figure(figsize=(10,6))
plt.hist(data['alcohol'],bins=20,edgecolor='black') #what is bins
plt.title('Histogram of alcohol')
plt.xlabel('Alcohol(%)')
plt.ylabel('Frequency')
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
data=pd.read_csv('PS_dataset.csv')
plt.figure(figsize=(10,6))
group_data=[data[data['quality']==q ]['residual sugar'].dropna() for q in sorted(data['quality'].unique())]
plt.boxplot(group_data,labels=sorted(data['quality'].unique()),patch_artist=True)
plt.title('Boxplot of Residual Sugar grouped by Quality Score')
plt.xlabel('Quality Score')
plt.ylabel('Residual Sugar ')
plt.show()

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline
import pandas as pd
import matplotlib.pyplot as plt
sample_rate=100
df = pd.read_csv('PS_dataset.csv')
df['Days'] = range(1, len(df)+1)
plt.figure(figsize=(10, 6))
plt.plot( df['Days'][::sample_rate],df['free sulfur dioxide'][::sample_rate], marker='x', label='free sulfur dioxide', color='blue')
plt.plot(df['Days'][::sample_rate], df['total sulfur dioxide'][::sample_rate], marker='o', label='total sulfur dioxide', color='red')
plt.title('Trend of Total Sulfur Dioxide vs Free Sulfur Dioxide')
plt.xlabel('Days')
plt.ylabel('Sulfur Dioxide Concentration ')
plt.legend()
plt.grid()
plt.show()

import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
data = pd.read_csv('PS_dataset.csv')
correlation_matrix = data.corr()
plt.figure(figsize=(12, 8))
sns.heatmap(correlation_matrix, annot=True, cmap='viridis', fmt=".2f", linewidths=0.5)
plt.title('Correlation Matrix Heatmap')
plt.show()

#bonus_basicexploration_q1
import pandas as pd
data=pd.read_csv('PS_dataset.csv')
mean=data['citric acid'].mean()
print(f"{mean}")

#advanceinsights_q1
import pandas as pd
dt=pd.read_csv('PS_dataset.csv')
dt['acidity_ratio']=dt['fixed acidity']/dt['volatile acidity']
print(dt['acidity_ratio'].head())

#datacleaningi_q1
import pandas as pd
df=pd.read_csv('PS_dataset.csv')
null_count=df['citric acid'].isnull().sum()
print(null_count)
median=df['citric acid'].median()
df['citric acid'].fillna(median)
print(df['citric acid'].head())

#g_a_q1
import pandas as pd
df=pd.read_csv('PS_dataset.csv')
average_alcohol_by_quality = df.groupby('quality')['alcohol'].mean()
highest_avg_alcohol_quality = average_alcohol_by_quality.idxmax()
print(f"For the quality score {highest_avg_alcohol_quality} has the highest average")

#basic_q2
import pandas as pd
df = pd.read_csv('PS_dataset.csv')
max_1 = df.max()
min_1 = df.min()

print("Maximum values in each column:\n", max_1)
print("\nMinimum values in each column:\n", min_1)

#g_a_q2
import pandas as pd
data=pd.read_csv('PS_dataset.csv')
mean=data.groupby('quality').mean()
median=data.groupby('quality').median()
print(f"Mean values grouped by quality\n{mean}")
print(f"\nMedian values grouped by quality\n{median}")

#f_c
import pandas as pd
dt=pd.read_csv('PS_dataset.csv')
filter=dt[(dt['pH']>3.5) & (dt['alcohol']>10)]
mean=filter['quality'].mean()
print(f"Mean of the quality with pH greater than 3.5 and alcohol content greater than 10 is {mean} ")

#datacleaningi_q2
import pandas as pd
dt=pd.read_csv('PS_dataset.csv')
filter=dt[(dt['residual sugar']).notna()]

#datacleaningi_q3
import pandas as pd
dt=pd.read_csv('PS_dataset.csv')
max=dt['fixed acidity'].max()
min=dt['fixed acidity'].min()
dt['Normalized fixed acidity']=(dt['fixed acidity']-min)/(max-min)
print(dt[['fixed acidity', 'Normalized fixed acidity']].head())

#datacleaningi_q4
import pandas as pd
df = pd.read_csv('PS_dataset.csv')
df_cleaned = df.drop_duplicates()

#advance_q2
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns
dt = pd.read_csv('PS_dataset.csv')
plt.figure(figsize=(13, 7))
sns.violinplot(x='quality', y='fixed acidity', data=dt, inner='quartile', palette='muted')
plt.title('Violin Plot of Fixed Acidity by Quality Score')
plt.xlabel('Quality Score')
plt.ylabel('Fixed Acidity ')
plt.show()

#advance_q3
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt
dt = pd.read_csv('PS_dataset.csv')
sns.pairplot(df)
plt.show()

